### PR TITLE
PAYARA-2184 PAYARA-1960 too many threads created

### PR DESCRIPTION
**Pull request by lprimak**
Tested with the algorithm test program
Added unit tests

### CODE REVIEW

**Comment by lprimak** [comment]
@pdudits @chrjohn
Can you please review this change to see if it will break anything before we release it

Unfortunately, due to the fix for
https://github.com/payara/Payara/issues/1869

the algorithm started creating way too many threads in an unbounded pool scenario,
leading to out-of-memory errors.
This PR is meant to fix it and not break anything else.

**Comment by pdudits** [comment]
I'll have a look at it tomorrow

**Comment by lprimak** [comment]
thanks @pdudits

**Comment by lprimak** [comment]
Patched Projects PR: https://github.com/payara/Payara_PatchedProjects/pull/84

**Review by Pandrex247 — APPROVED** [review]

**Review by pdudits — COMMENTED** [review]
I am bit scared of this invasive adaptation of ThreadPoolExecutor - while it works for JDK8, the reflection access will  fail in JDK9.

I would be much more confident with implementation of
[woraround #2 from this article](https://dzone.com/articles/scalable-java-thread-pool-executor#article-signin-prompt) - to do direct transfer first, and if the task is rejected, put it into queue.

I think we don't need custom rejection handlers here, and if so, we would only need to override setRejectionHandler() to keep our logic in the chain first.

This approach is probably also more performant, as getActiveCount() requires global lock.

**Comment by lprimak** [comment]
Will use PR #4 instead

**Pull request closed without merging**
